name: Integration Testing

on:
  push:
    branches: ["api"]


jobs:
   Paralell-Testing:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Install-python
         uses: actions/setup-python@v4
         with: 
           python-version: '3.10' 
           cache: true
   
       - name: Checkout
         uses: actions/checkout@v4

       - name: Install-python
         uses: actions/setup-python@v4
         with: 
           python-version: '3.11' 
           cache: true
                  
